### ISSUE TITLE
getCurrentPosition is not a function 

### ISSUE THREAD

**Issue by winyluo** [Silverbase-FE/cordova-plugin-amap#11]
插件报错getCurrentPosition is not a function 是什么问题
打印：AMapPlugin ，显示的是function(){},
麻烦解答一下，谢谢 @Rain1368189893

**Comment by liveKang** [comment]
你确认下插件是否成功安装，重新安装试下。 @winyluo

**Comment by winyluo** [comment]
不行啊，我在amap.js 里面改成了var AMapPlugin = {};这样不报错 但函数还是没有调用 @Rain1368189893

**Comment by liveKang** [comment]
已经发布新的版本。
