### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by mengkeys** [Silverbase-FE/cordova-plugin-amap#12]
Error: Unexpected close tag

**Comment by liveKang** [comment]
能稳定重现吗？可否贴下截图日志看下。@mengkeys

**Comment by mengkeys** [comment]
这个插件能在ionic3 + android-cordova@6.4.0下使用吗？

**Comment by liveKang** [comment]
是可以的，但是现在好像出了些问题，正在升级中。

**Comment by liveKang** [comment]
@mengkeys  更正下，插件需要在 cordova-android@~7.0.0 使用，目录结构发生了变化，[Cordova Android 7.0.0 Released!](https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html)
