### ISSUE TITLE
是否支持cordova中打开高德地图，并定位到某个坐标

### ISSUE THREAD

**Issue by 349989153** [Silverbase-FE/cordova-plugin-amap#17]
您好，我快速地浏览了一遍readme.md，似乎没有看到我需要的功能，所以我想直接向您确认一下，如果太唐突，请您多多包涵。

我的问题是：能否在cordova app中，直接调您的库的API，传入一个经纬度，然后您的库会调起高德地图app，并把地图的中心点置为传入的经纬度

**Comment by Rain1368189893** [comment]
AMapPlugin.showMap

**Comment by liveKang** [comment]
@349989153   [AMapPlugin.showMap](https://github.com/Silverbase-FE/cordova-plugin-amap/blob/master/www/amap.js)
