### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by subenkun** [Silverbase-FE/cordova-plugin-amap#5]
环境信息：
cli packages: (/Users/developer/.nvm/versions/node/v8.9.0/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1

错误信息：
(node:5322) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Unexpected close tag
Line: 150
Column: 15
Char: >
(node:5322) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

试了两台机器，错误信息都一样。

**Comment by liveKang** [comment]
嗯，现在还有些问题。新的ionic3的demo 和 plugins 很快将会出来。

**Comment by subenkun** [comment]
谢谢，迫不及待

2018-01-26 12:12 GMT+08:00 飘香 <notifications@github.com>:

**Comment by liveKang** [comment]
This issue has been solved.
