### ISSUE TITLE
定位返回结果只有provinceName

### ISSUE THREAD

**Issue by subenkun** [Silverbase-FE/cordova-plugin-amap#7]
每次定位只返回provinceName，ios11、ios10同样结果。
![547795a27cfb974dec8a5a700189a1d4](https://user-images.githubusercontent.com/902220/36769475-738b6a66-1c7f-11e8-82eb-718c9179553f.png)

**Comment by liveKang** [comment]
![31519792016_ pic](https://user-images.githubusercontent.com/15951791/36769995-b81cb65a-1c82-11e8-850c-9bd8c608bee3.jpg)
![31519792016_ pic](https://user-images.githubusercontent.com/15951791/36770004-c237c350-1c82-11e8-816c-35b8f8810ac5.jpg)
我刚才跑了下demo，发现没这个问题。你是用的真机吗？有没有什么日志？

**Comment by liveKang** [comment]
![21519792016_ pic](https://user-images.githubusercontent.com/15951791/36770029-e97a0400-1c82-11e8-8e7e-e092dfe2395f.jpg)

**Comment by subenkun** [comment]
![d6ff8df4-b3fb-4648-bff5-1f65d0802a82](https://user-images.githubusercontent.com/902220/36770996-9dfb758a-1c88-11e8-9cff-70bb7f75eb88.png)
另外定位速度是否可以优化下。
android打包报错：
![677e9fc8-8836-475b-b787-338df430bf17](https://user-images.githubusercontent.com/902220/36771772-6b06b2b6-1c8d-11e8-9e89-346ca19b1f56.png)

**Comment by liveKang** [comment]
![image](https://user-images.githubusercontent.com/15951791/36773557-3924c99c-1c95-11e8-8891-53d52b9f4853.png)
Android下报错的问题，你把上图所示的三个jar包，Add As Library就可以了。这里需要手动Add下。
定位的速度的精度有关系。
![image](https://user-images.githubusercontent.com/15951791/36773723-ff372468-1c95-11e8-9a2d-9d270b4a3171.png)

**Comment by subenkun** [comment]
精度等参数支持options的方式传入就更完美了
