### ISSUE TITLE
请问这个插件是用在cordova的哪个版本上的？

### ISSUE THREAD

**Issue by tichaun** [Silverbase-FE/cordova-plugin-amap#9]
![image](https://user-images.githubusercontent.com/23025317/40599580-65f188f8-6280-11e8-8c83-0d0730f25e19.png)
build 的时候报错说插件的Java代码不对

**Comment by Rain1368189893** [comment]
把错误提示贴一下。cordova 7.1.0及以上

**Comment by liveKang** [comment]
把错误提示贴一下。cordova 7.1.0及以上 @tichaun

**Comment by tichaun** [comment]
![image](https://user-images.githubusercontent.com/23025317/40697193-aff6d724-63fb-11e8-9adb-60e51ca5ba2c.png)
![image](https://user-images.githubusercontent.com/23025317/40697218-d9390e2c-63fb-11e8-924f-eb2ae01849d4.png)
![image](https://user-images.githubusercontent.com/23025317/40697271-0a4728d2-63fc-11e8-8eab-8a458a6db1f9.png)
并没有生成的 MainActivity.java 文件

**Comment by tichaun** [comment]
@Rain1368189893

**Comment by liveKang** [comment]
把三个jar包文件 Add到项目中。参照下[issues7](https://github.com/Silverbase-FE/cordova-plugin-amap/issues/7) @tichaun

**Comment by tichaun** [comment]
@Rain1368189893 
![image](https://user-images.githubusercontent.com/23025317/40698000-8281bb84-63ff-11e8-85fd-14c23180fe0d.png)这三个jar包都有的

**Comment by liveKang** [comment]
三个jar包是通过cordova XML从plugins复制过来的，需要手动添加到项目中，具体操作：单个选中右击，选择Add As Library，三个依次进行，添加成功后的jar包是可以展开的，如图：
![image](https://user-images.githubusercontent.com/15951791/40698147-3f287c0a-6400-11e8-9827-aa64446a95d2.png)
@tichaun

**Comment by tichaun** [comment]
![image](https://user-images.githubusercontent.com/23025317/40702688-5ccb7108-6415-11e8-86bb-5031a62a884a.png)
上面那个amap文件夹是我从你们那个项目里复制过去的，三个jar包也add了，打包还是报错
![image](https://user-images.githubusercontent.com/23025317/40702763-a2813c8c-6415-11e8-9c71-b1e081c4b309.png)
@Rain1368189893

**Comment by liveKang** [comment]
![image](https://user-images.githubusercontent.com/15951791/40703520-fe604d70-6417-11e8-9677-d0ab1fb2bdd0.png)
刷新下all gradle projects试下，relese版本是需要签名证书的，你配置了没？先运行`ionic cordova build android`,看看能否正常生成debug版本？ @tichaun

**Comment by tichaun** [comment]
![image](https://user-images.githubusercontent.com/23025317/40711262-50aff4c6-642d-11e8-8850-cf3b4ff4ce5e.png)
我感觉马上要成功了，这个怎么弄 @Rain1368189893

**Comment by liveKang** [comment]
红色框中，com.amap.plugin 是app包名，你替换成你app的包名 @tichaun

**Comment by tichaun** [comment]
@Rain1368189893 非常感谢，打包成功了，但是扔然定位不到，我alert(AMapPlugin) 弹出的是 function(){},成功的回调和错误的回调里的alert都没有弹出，查看了一下签名是对的，目前不知道是什么原因了

**Comment by liveKang** [comment]
可能是gps权限的问题，你的测试机是什么机型，什么系统版本的。 @tichaun

**Comment by tichaun** [comment]
@Rain1368189893 定位权限是开这的，第一次点击定位的时候会谈出是否授权，手机是锤子坚果pro,系统型号安卓7.1.1

**Comment by liveKang** [comment]
你尝试连续调用api，或者调用其他的api，看看是否会报错，排除高德key和SHA1的因素 @tichaun

**Comment by tichaun** [comment]
@Rain1368189893 


![55](https://user-images.githubusercontent.com/23025317/40757672-3e967a28-64bc-11e8-86a7-599855df8239.png)

这事我点击定位是的log日志信息，感觉这是定位的，但是没有给我返回定位结果

**Comment by liveKang** [comment]
![image](https://user-images.githubusercontent.com/15951791/40760638-362d7f86-64ca-11e8-9ebd-6252d32c8c3a.png)
这里不是有结果吗？ @tichaun  你对照下是否精确

**Comment by tichaun** [comment]
对的，这个是定位到的信心，但是没有返回到页面上，回调方法并没有收到




| |
H5开发工程师
邮箱：17601444512@163.com
|

签名由 网易邮箱大师 定制

在2018年05月31日 12:01，飘香 写道：


这里不是有结果吗？ @tichaun 你对照下是否精确

**Comment by liveKang** [comment]
贴一下你获取回调的代码 @tichaun ，你也可以参照 [示例](https://github.com/Silverbase-FE/testApp-plugin-amap/blob/master/src/app/app.component.ts)

**Comment by tichaun** [comment]
![image](https://user-images.githubusercontent.com/23025317/40816583-4d22de8c-6580-11e8-989a-3f1d4538887b.png)
只打印了 1 ，其余的都没打印也没alert @Rain1368189893

**Comment by liveKang** [comment]
打印下 `AMapPlugin` 对象在1后面，`setInterval(AMapPlugin.getCurrentPosition(...), 3000)` 连续调下看看，你的这个代码在`deviceReady`状态下的吧 @tichaun

**Comment by tichaun** [comment]
![image](https://user-images.githubusercontent.com/23025317/40817087-ff299af6-6582-11e8-84ce-9c75ee37c430.png)
还是不行的，不过非常感谢您的回答，希望这个插件可以继续改进

**Comment by liveKang** [comment]
插件已经改进，欢迎再试。
